// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Backbone.Detour = (function(_super) {

    __extends(Detour, _super);

    function Detour() {
      return Detour.__super__.constructor.apply(this, arguments);
    }

    Detour.prototype.routes = {
      '*path': 'routeHandler'
    };

    Detour.prototype.routeHandler = function(route) {
      var args,
        _this = this;
      args = this.parseRoute(route);
      _.each(this.paramsForRoute, function(pfr) {
        var val, _ref;
        val = args[pfr.name];
        if (((_ref = pfr.type) != null ? _ref.toLowerCase() : void 0) === 'array') {
          val = (val != null ? typeof val.split === "function" ? val.split(',') : void 0 : void 0) || val;
        }
        return args[pfr.name] = val;
      });
      if (!this.previousValues) {
        this.previousValues = {};
      }
      _.each(args, function(v, k) {
        return _this.previousValues[k] = v ? v : false;
      });
      return this.handleRoute(args);
    };

    Detour.prototype.parseRoute = function(route) {
      var keys, o, vals;
      if (this.paramsForRoute == null) {
        this.paramsForRoute = [];
        this.routeOptions();
      }
      keys = [];
      vals = [];
      if (route) {
        _.each(route.split('/'), function(v, i) {
          return (i % 2 === 0 ? keys : vals).push(v);
        });
      }
      vals = _.map(vals, function(val) {
        return decodeURI(val);
      });
      o = _.object(keys, vals);
      _.each(this.paramsForRoute, function(opt) {
        if (opt["default"] != null) {
          if (!o[opt.name]) {
            return o[opt.name] = (typeof opt["default"] === "function" ? opt["default"]() : void 0) || opt["default"];
          }
        }
      });
      return o;
    };

    Detour.prototype._isArray = function(value) {
      return value && typeof value === 'object' && value instanceof Array && typeof value.length === 'number' && typeof value.splice === 'function' && !(value.propertyIsEnumerable('length'));
    };

    Detour.prototype.buildRoute = function(opts) {
      var options, r, required, requiredNotSet, rs,
        _this = this;
      if (opts == null) {
        opts = {};
      }
      options = {};
      if (!this.previousValues) {
        this.previousValues = {};
      }
      _.each(this.paramsForRoute, function(pfr) {
        var clears, comparator, prevVal, prevVals, pv, val, vals, _i, _len, _ref;
        prevVal = _this.previousValues[pfr.name];
        val = opts[pfr.name] === false ? ((typeof pfr["default"] === "function" ? pfr["default"]() : void 0) || pfr["default"]) || false : opts[pfr.name] ? opts[pfr.name] : prevVal || ((typeof pfr["default"] === "function" ? pfr["default"]() : void 0) || pfr["default"]) || false;
        if ((pfr.squash != null) && val === pfr.squash) {
          val = false;
        }
        if ((prevVal != null) && val !== prevVal && (pfr.clears != null)) {
          clears = _this._isArray(pfr.clears) ? pfr.clears : [pfr.clears];
          _.each(clears, function(clear) {
            options[clear] = false;
            return opts[clear] = false;
          });
        }
        if (val && ((_ref = pfr.type) != null ? _ref.toLowerCase() : void 0) === 'array' && pfr.append) {
          vals = val;
          prevVals = prevVal || [];
          for (_i = 0, _len = prevVals.length; _i < _len; _i++) {
            pv = prevVals[_i];
            if (vals.length !== (pfr.appendLimit || 99)) {
              if (pfr.unique) {
                comparator = pfr.comparator || function(a, b) {
                  return a === b;
                };
                if (__indexOf.call(_.map(vals, function(val) {
                  return comparator(val, pv);
                }), true) < 0) {
                  vals.push(pv);
                }
              } else {
                vals.push(pv);
              }
            }
          }
          val = typeof vals.join === "function" ? vals.join(',') : void 0;
        }
        return options[pfr.name] = val;
      });
      required = _.filter(this.paramsForRoute, function(opt) {
        return opt.required;
      });
      requiredNotSet = __indexOf.call(_.map(required, function(req) {
        return options[req.name] || false;
      }), false) >= 0;
      if (requiredNotSet) {
        r = '';
      } else {
        rs = [];
        _.each(this.paramsForRoute, function(pfr) {
          if (options[pfr.name]) {
            return rs.push("" + pfr.name + "/" + (encodeURI(options[pfr.name])));
          }
        });
        r = rs.join("/");
      }
      return r;
    };

    Detour.prototype.updateRoute = function(opts) {
      return this.navigate(this.buildRoute(opts), {
        trigger: true
      });
    };

    Detour.prototype.optional = function(name, opts) {
      if (opts == null) {
        opts = {};
      }
      opts.name = name;
      return this.paramsForRoute.push(opts);
    };

    Detour.prototype.required = function(name, opts) {
      if (opts == null) {
        opts = {};
      }
      opts.name = name;
      opts.required = true;
      return this.paramsForRoute.push(opts);
    };

    Detour.prototype.routeOptions = function() {};

    Detour.prototype.handleRoute = function(args) {};

    return Detour;

  })(Backbone.Router);

}).call(this);
