// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Router = (function(_super) {

    __extends(Router, _super);

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.initialize = function(args) {};

    Router.prototype.routeOptions = function() {
      return this.optional('section', {
        "default": 'intro'
      });
    };

    Router.prototype.classify = function(str) {
      return str.charAt(0).toUpperCase() + str.slice(1);
    };

    Router.prototype.handleRoute = function(args) {
      var view;
      view = Views[this.classify(args.section)];
      if (view) {
        $('body').html(new view().render(this.prev).el);
        this.prev = "#section/" + args.section;
        return console.log(this.prev);
      }
    };

    return Router;

  })(Backbone.Detour);

}).call(this);
